name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup MsBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Debug
        run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Debug SealighterTI.sln

      - name: Build Release
        run: msbuild.exe /nologo /m /t:Rebuild /p:Configuration=Release SealighterTI.sln
